### ISSUE TITLE
Kubernetes Strategy: Why do node names need to be the same?

### ISSUE THREAD

**Issue by isaacsanders** [bitwalker/libcluster#100]
If I missed an issue where this is discuss, I'd appreciate knowing where read up.

If this hasn't been discussed before, I would be interested in understanding.

Why do nodes need to have the same basename? Nodes with different names can connect to one another in dist erl, and all is needed is a shared cookie, and nodes that can find other nodes will connect.

Is this just something that this library hadn't decided to support? Is there a reason that this doesn't work that I'm missing?

**Comment by bitwalker** [comment]
To connect two Erlang nodes, they don't need to have the same basename; just some basename, a routable hostname, and as you mentioned, the same cookie. A `libcluster` strategy must know how to map a hostname/IP to a fully-qualified node name, i.e. `<basename>@<hostname_or_ip>`. Most strategies find nodes in such a way that the basename cannot be inferred, so it must be defined statically - which is rarely an issue since it is easy enough to ensure all nodes in a cluster use a uniform basename, and generally speaking basenames tend to be the same for all nodes in a cluster anyway. 

It is possible that you may have different basenames for necessary reasons, but without a way to know what basename a given node is using, we have to rely on that being statically defined by default. However, it is supported to provide your own connect/disconnect handlers which can map between a "raw" name and the correctly mapped name. The raw name would be the default produced by the strategy, i.e. you specify that all nodes have the basename `app`. Your own `connect` or `disconnect` handler could then map from `app@<hostname_or_ip>` to `<mapped_basename>@<hostname_or_ip>` and then call the default connect/disconnect functions, i.e. `:net_kernel.connect_node/1`, `:erlang.disconnect_node/1` respectively.

Erlang nodes don't necessarily always form a mesh either, you can provide a VM flag that will prevent a node from connecting to other nodes implicitly and vice versa. The way `libcluster` works ensures that it is compatible with clusters formed in ways that don't rely on the default meshing behavior (i.e. if you use something like Partisan and form clusters that are more like a tree than a mesh).

**Comment by isaacsanders** [comment]
Cool. Thanks for the detailed response.

So a strategy could be implemented that relied more heavily on something, like a label value in Kubernetes?

Would that be something you would be interested in having contributed as an option to the existing strategy?

**Comment by bitwalker** [comment]
It is definitely possible to define, and I'm certainly fine with, strategies which have additional options to take advantage of metadata they have available. So to use your example of Kubernetes, allowing users to specify that they would like to derive the node basename from a label, rather than hardcoding it.

The defaults should always be based on a static nodename, since that will make the default behavior of all the strategies uniform on this front; but per-strategy extensions are definitely acceptable.

**Comment by VictorGaiva** [comment]
> and generally speaking basenames tend to be the same for all nodes in a cluster anyway.
I currently work with a scenario where we deploy multiple releases coming from the same Umbrella app. Each release has some features that are not needed by others, for example:

- Gateway: Main Phoenix entry point for our users, that should be as stable as possible.
- Runner: Responsible for running jobs, that should be able to scale horizontally and might sometimes OOM due to some jobs running ChromicPDF, but that's OK since it just restarts and retries the job.
- ... and some others

In this case, the nodename of each app is derived from the `app` label on our kubernetes deployment, which in turn make each app have different basenames for each release/deployment.

We follow a hexagonal architecture, and all releases share a same 'core' as a dependency umbrella app, which is were we call LibCluster. Currently we define that all apps try to connect to the `gateway` app. Since it must always be present, and after a node connects it discovers the rest of the nodes by itself.

What you are saying is that it would be better for all the releases to have the same "<example>" basename, even if they are naturally different apps?
