### ISSUE TITLE
Kubernetes config missing keys

### ISSUE THREAD

**Issue by mrkaspa** [bitwalker/libcluster#14]
What should be the connect: and disconnect: values for a kubernetes configuration, they are being read here https://github.com/bitwalker/libcluster/blob/master/lib/strategy/kubernetes.ex#L39 but  they aren't set in the example configuration https://github.com/bitwalker/libcluster/blob/master/lib/strategy/kubernetes.ex#L15

**Comment by bitwalker** [comment]
You can view their default values [here](https://github.com/bitwalker/libcluster/blob/master/lib/app.ex#L19). They are effectively hidden settings for the time being, but were implemented in the strategy behaviour in order to lay the groundwork for being able to use other protocols for distribution, they do not need to be set currently.
