### ISSUE TITLE
poison 3.0 dependency is aggressive

### ISSUE THREAD

**Issue by ijcd** [bitwalker/libcluster#15]
Is it necessary to have such an aggressive poison dependency? Being a library, libcluster should be as conservative as it can here, otherwise it makes it difficult to use with other libraries.

```
Failed to use "poison" (versions 1.5.0 to 1.5.2) because
  deps/libcluster/mix.exs requires ~> 3.0
  ex_aws (versions 1.0.0 to 1.1.2) requires >= 1.2.0
  mix.exs specifies ~> 1.5
```

**Comment by bitwalker** [comment]
Just put `{:poison, "~> 1.5.0", override: true}` in your deps, it should work fine as I'm not using any newer features of Poison. That said, I tested with 3.0, so that's what I put the dependency at. Consumers of the library always have the option of overriding the dependency version if they need to for some reason. 3.0 has been around for quite awhile now (at least 6 months at this point), so it's definitely not what I would call "aggressive".

**Comment by manju16832003** [comment]
It throws error if we use `{:libcluster, "~> 2.1"}`
```
Failed to use "poison" (versions 1.5.0 to 2.2.0) because
  libcluster (version 2.1.0) requires ~> 3.0
  phoenix (versions 1.2.1 to 1.2.3) requires ~> 1.5 or ~> 2.0
```
This would fix the issue overriding poision `{:poison, "~> 1.5.0", override: true}`

However, `{:libcluster, "~> 2.0"}` this works well, without any issue with poison

**Comment by bitwalker** [comment]
Yes, as mentioned previously, if you need to use an older version of Poison, you will need use `override: true` on the dependency.
