### ISSUE TITLE
crypto:block_encrypt/4 is removed in OTP 24

### ISSUE THREAD

**Issue by burmajam** [bitwalker/libcluster#158]
Gossip doesn't work anymore with OTP 24 since :crypto..block_encrypt/4 is removed:

```
** (UndefinedFunctionError) function :crypto.block_encrypt/4 is undefined or private
    (crypto 5.0) :crypto.block_encrypt(:aes_cbc256, <<...>>)
    (libcluster 3.2.2) lib/strategy/gossip.ex:264: Cluster.Strategy.Gossip.encrypt/2
    (libcluster 3.2.2) lib/strategy/gossip.ex:227: Cluster.Strategy.Gossip.heartbeat/2
```

**Comment by bitwalker** [comment]
Fixed in master, and in the soon to be released v3.3.0

**Comment by burmajam** [comment]
With updated lib old error message is gone but new one appeared:

```
[error] GenServer #PID<0.5792.0> terminating
** (stop) {:badarg, {'api_ng.c', 141}, 'Unknown cipher'}
    (crypto 5.0) :crypto.ng_crypto_one_time_nif(:aes_cbc256, <<...>>, true, :undefined)
    (libcluster 3.3.0) lib/strategy/gossip.ex:264: Cluster.Strategy.Gossip.encrypt/3
    (libcluster 3.3.0) lib/strategy/gossip.ex:227: Cluster.Strategy.Gossip.heartbeat/2
```

**Comment by svrdlans** [comment]
This might be helpful - `:aes_cbc256` is a retired cypher name, here is a list of mappings to new names


Instead of: | Use:
-- | --
aes_cbc128 | aes_128_cbc
aes_cbc256 | aes_256_cbc
aes_cbc | aes_128_cbc, aes_192_cbc, aes_256_cbc
aes_ccm | aes_128_ccm, aes_192_ccm, aes_256_ccm
aes_cfb128 | aes_128_cfb128, aes_192_cfb128, aes_256_cfb128
aes_cfb8 | aes_128_cfb8, aes_192_cfb8, aes_256_cfb8
aes_ctr | aes_128_ctr, aes_192_ctr, aes_256_ctr
aes_gcm | aes_128_gcm, aes_192_gcm, aes_256_gcm
des3_cbc | des_ede3_cbc
des3_cbf | des_ede3_cfb
des3_cfb | des_ede3_cfb
des_ede3 | des_ede3_cbc
des_ede3_cbf | des_ede3_cfb
