### ISSUE TITLE
New Strategy:  DNS or Consul based discovery

### ISSUE THREAD

**Issue by arianvp** [bitwalker/libcluster#20]
Would you be interested in a PR adding Consul and (m)DNS based clustering support?  

Consul: We can listen to consul services and if a new member is added to a server, we consider it part of the erlang cluster.

We could also generalise this using DNS.  you make a SRV request to `workers.my-internal.network.local` and see how many records come back and join these in the cluster.  (Consul gives us such a DNS based interface).  I think actually, this implementation would both generalise the Kubernetes and the Consul strategies, as Kubernetes exposes services using KubeDNS. 

We could further generalise this to `mDNS` which uses multicast UDP to find peers. Similar to the current multicast discovery protocol, but standardised by RFC.

I have some free time this summer, and I would like to work on it to learn some erland and elixir.
I was wondering if you already gave this thought before, and if you have any suggestions in this direction.

**Comment by bitwalker** [comment]
@arianvp Definitely! I'd be glad to merge the DNS-based strategy, whichever route you think is most useful. I would prefer to leave the Consul-specific implementation to a third party library though, since I will be unable to maintain it myself. I probably should split out the Kubernetes strategy for that matter, just to be consistent - but haven't found the time to do so.

Let me know if you have any questions for me, and I'll get back to you ASAP!

**Comment by praseodym** [comment]
A DNS-based strategy could work for Kubernetes as well, by leveraging [headless services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services).

**Comment by doughsay** [comment]
Has any work been done on a DNS strategy yet?  If not, I think I'll take a stab at it, since I think I need it now too...

I haven't been able to get any of the other strategies to work for me in all my environments.  I basically need something that will work in both a kubernetes environment AND non-kubernetes (in my case docker-compose).  The kubernetes strategy works great for my production environment, but not in testing and local environments.  The gossip strategy works great for those, but then doesn't work in kubernetes...  DNS sounds like it'll work in both.

**Comment by bitwalker** [comment]
@doughsay It seems like @arianvp has not yet been able to get around to it, so it's wide open if you want to take a crack at it :). I'd be glad to merge it!

**Comment by meatherly** [comment]
Has anyone created the consul strategy yet?

**Comment by bitwalker** [comment]
@meatherly Not that I'm aware of, so feel free to take a stab at it :)

**Comment by arcz** [comment]
@meatherly I've been working on one, just published here https://github.com/arcz/libcluster_consul it should be kinda usable but requires more work

**Comment by bitwalker** [comment]
I'll add it to the README :)

**Comment by arianvp** [comment]
Nice :).  I'll see if I can tackle the DnS based one later. But no need to
keep the issue open for that in my opinion.

**Comment by kpanic** [comment]
also I found https://github.com/uberbrodt/caravan
