### ISSUE TITLE
Consider removing Cluster.Events

### ISSUE THREAD

**Issue by josevalim** [bitwalker/libcluster#6]
Firenest will be able to abstract nodeup/nodedown events and someone can use Firenest.PubSub if they want distributed events (as @gmile asked in #2).

**Comment by bitwalker** [comment]
Implemented in 1b4dfe6

**Comment by sb8244** [comment]
@bitwalker is there any benefit in reviving `Cluster.Events` since Firenest is no longer in development?

I got here because I was trying to find a source for `"It provides a publish/subscribe mechanism for cluster events so that you can easily be notified when cluster members join or leave"` in master branch's README.

**Comment by entone** [comment]
@sb8244 you can use :net_kernel.monitor_nodes to achieve the same thing.

That's what Swarm utilizes.

**Comment by sascha-wolf** [comment]
> @bitwalker is there any benefit in reviving `Cluster.Events` since Firenest is no longer in development?
> 
> I got here because I was trying to find a source for `"It provides a publish/subscribe mechanism for cluster events so that you can easily be notified when cluster members join or leave"` in master branch's README.

+1, IMO either libcluster should revive `Cluster.Events` or remove the mentioning of a "publish/subscribe mechanism" in the README. I was very confused trying to find said mechanism until I ended up here.
