### ISSUE TITLE
Libcluster running as a dependency for multiple apps in an umbrella

### ISSUE THREAD

**Issue by cburman01** [bitwalker/libcluster#85]
Experiencing an odd issue with libcluster. Using the EPMD strategy.
Setup: 
Multiple apps under a single umbrella. Distillery targeted releases for certain apps within the umbrealla. 

Each app runs as a single systemd service and each service must connect to each other. 

What we are noticing is only one EPMD process gets started on the box, not one per service, but only the first service that gets started. 

This causes issues like if service 1 goes down, service 2 is unable to connect to service 1 if he gets restarted. 

I would expect that service 1 and service 2 both have epmd process running. 

Is my understanding correct? I am really just fishing here. Let me know if you need anything from me.

**Comment by cmeiklejohn** [comment]
Distributed Erlang only launches a single EPMD on the machine and is launched by demand by the process that's first starting Distributed Erlang, unless you specify the option to not start EPMD.  `epmd -names` should return the list of all connected VMs.   The reason for this is because it listens on a fixed port, and only once instance can bind that.  This problem of having an EPMD die and causing all of the nodes to be disconnected is a well known issue with EPMD.

**Comment by bitwalker** [comment]
As Chris said, this is a known issue, but also an unfortunate side effect of how `epmd` is setup to work. If I understand your setup and the issue you are having correctly, I believe the solution in your case is to run `epmd` as its own service, and not rely on it to be started by your application, since I suspect systemd is killing it when your application dies for some reason (since it is effectively a child of that process).

**Comment by cmeiklejohn** [comment]
One solution we used around 3 years ago at Mesosphere, was to have an EPMD container, and then had container dependencies on the app containers to EPMD, and then do a restart strategy where all were restarted when EPMD was, but that's less than ideal.

**Comment by bitwalker** [comment]
Good point, you'd want to do the same thing with systemd unit dependencies to make sure that it gets started before your app does, and that your app is restarted if epmd goes down, something like the following:

```
After=epmd.service
Requires=epmd.service
PartOf=epmd.service
```

**Comment by cburman01** [comment]
Thanks guys. I started EPMD as its own service and now it works great!
